version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels: ["security", "dependencies"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels: ["security", "dependencies"]

  - package-ecosystem: "pip"
    directory: "/k8s/rabbitmq"
    schedule:
      interval: "weekly"
      day: "monday"
    labels: ["security", "dependencies"]

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
    labels: ["security", "dependencies"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels: ["security", "dependencies"]
